---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'CloudWatch Alarm to Slack'
Parameters:
  WebhookURL:
    Description: 'Slack incoming webhook URL'
    Type: String
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'handler.processEvent'
      Runtime: 'nodejs12.x'
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref Topic
  ErrorsTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Invocations failed due to errors in the function'
      Namespace: 'AWS/Lambda'
      MetricName: Errors
      Dimensions:
      - Name: FunctionName
        Value: !Ref LambdaFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      TreatMissingData: notBreaching
      AlarmActions:
      - !Ref Topic
